apply plugin: 'com.android.library'

android {
    namespace 'com.tront.eosnative'
    compileSdk 35

    defaultConfig {
        minSdk 23
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    compileOnly fileTree(dir: project.rootDir, include: ['**/eossdk*.aar'])
}
