apply plugin: 'com.android.library'

android {
    compileSdkVersion 33
    buildToolsVersion '30.0.3'

    defaultConfig {
        minSdkVersion 23
        targetSdkVersion 33
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    // The EOS SDK AAR is added to the project by Unity as a separate dependency.
    // We need it at compile time to reference com.epicgames.mobile.eossdk.EOSSDK.
    // Search common locations Unity places AAR files in the generated Gradle project.
    compileOnly fileTree(dir: project.rootDir, include: ['**/eossdk*.aar'])
}
